# Alternately, comment the [database] section and
# set the enviroment variable
#
# DATABASE_URL="mysql://worker:root@192.168.1.10:3306/service"
[database]
address = "192.168.1.10"
port = 3306
username = "worker"
password = "root"
name = "service"

# Alternately, comment the [rabbit] section and
# set the enviroment variable
#
# AMQP_URL=amqp://worker:root@192.168.1.11:5672/vhost
[rabbit]
address = "192.168.1.11"
port = 5672
username = "worker"
password = "root"
vhost = "vhost"

# Alternately, comment the [log] section and
# set the enviroment variables (only RUST_LOG is fine)
#
# RUST_LOG="info"
# RUST_LOG_STYLE="auto"
#
# See https://doc.servo.org/env_logger/index.html
[log]
log = "debug"
style = "auto"